"""changed loan variables

Revision ID: 5dd0fa18f171
Revises: 2dbcce892d68
Create Date: 2024-12-06 15:21:44.780200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd0fa18f171'
down_revision = '2dbcce892d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('return_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
