"""empty message

Revision ID: b305295f943c
Revises: 3cee6e5eb0a1
Create Date: 2024-10-25 13:47:32.079675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b305295f943c'
down_revision = '3cee6e5eb0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessmentTitle', sa.String(length=100), nullable=False),
    sa.Column('moduleCode', sa.String(length=50), nullable=False),
    sa.Column('deadlineDate', sa.Date(), nullable=False),
    sa.Column('assessmentDescription', sa.String(length=255), nullable=False),
    sa.Column('assignmentStatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessmentTitle')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index('ix_property_address')

    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('rent', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index('ix_property_address', ['address'], unique=1)

    op.drop_table('assessment')
    # ### end Alembic commands ###
